### ISSUE TITLE
about new FTEX format file convert

### ISSUE THREAD

**Issue by KingFooZQ** [rufaswan/Web2D_Games#11]
Sorry to disturb you in this way, but there got a new format of FTEX file, it's from recently game Unicorn Overlord demo. cant convert it using "psxtools/*__FTEX.php".  maybe if you're interested

**Comment by KingFooZQ** [comment]
> Sorry to disturb you in this way, but there got a new format of FTEX file, it's from recently game Unicorn Overlord demo. cant convert it using "psxtools/*__FTEX.php". maybe if you're interested

[here is FTEX file link]( https://drive.google.com/drive/folders/1R083nowi4YH7vwLcVn5hR8-1t6KnYJZN?usp=sharing)

**Comment by rufaswan** [comment]
WOW! Files are extracted already? That was quick!

Which console is the files are from? Unicorn Overlord is available on PS4, PS5, Xbox Series X/S and Switch. If it is from PS4, you can try "ps4_13sent_FTEX.php" for 13 Sentinels FTEX files. I do not have FTEX.php script for other console yet.

But I can already tell both uploaded FTX are 1024x512 textures. I will update you when I made further progress.

Thanks!

**Comment by KingFooZQ** [comment]
Oh, I fotget to tell the console. It's from Unicorn Overlord Demo in Switch.  There also got other file format.  I send you an email. email address was found in your github overview,  there is share link of the extracted files.  Check if you're interested.   Also, thank you for your work.  Deeply appreciative！

**Comment by rufaswan** [comment]
I just replied your email. Let me know if you received it. Thanks!

**Comment by KingFooZQ** [comment]
![Worldmap_PositionCheck 0 nvt](https://github.com/rufaswan/Web2D_Games/assets/132016843/270934cb-5df7-414a-8259-7ba2b2cc52bc)
![St_OW_C_1 0 nvt](https://github.com/rufaswan/Web2D_Games/assets/132016843/8b91c1c1-412a-4d68-8f2b-7b0e1ec54f97)
The ftx files in the GUI folder, may have this kind of aliasing in the generated png

**Comment by rufaswan** [comment]
The graphic errors at the bottom are from texture swizzling. I updated the repo with a fix.

As for those aliasing, that is from the texture compression. BC7 is like JPEG, it is a lossy compression done in 4x4 pixel blocks. 

They say PS4 version is 4K HD, so it is 2x switch resolution. Aliasing will be much less noticeable there.

Let me know if you have any more errors. Thanks!

**Comment by rufaswan** [comment]
Hi @KingFooZQ , do you still have any more errors? If not, I'm going to close this issue as completed. Thanks!
