### ISSUE TITLE
PNG and nvt import

### ISSUE THREAD

**Issue by Sobarashi** [rufaswan/Web2D_Games#13]
Hi rufaswan
i have extract the font texture from ftx file from boath 13 Sentinels and Unicorn Overlord games
so is there a way to import it back after i edit the font

<img width="875" alt="2024-03-10 21_43_41-C__Windows_System32_cmd exe" src="https://github.com/rufaswan/Web2D_Games/assets/62736436/237a43f8-016b-4375-b447-82febdcdc3ce">

thanks in advance!

**Comment by rufaswan** [comment]
Hi! Unfortunately I do not have anything to import them back. My focus is only on ripping stuff out, not on putting them back in.

You may need to make a new tool for it yourself.

Good luck!

**Comment by Sobarashi** [comment]
thanks for you reply.
