### ISSUE TITLE
Request support for FTEX format 44

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [rufaswan/Web2D_Games#19]
```php
function switnvt( &$file, $base, $pfx, $id )
{
	printf("== switnvt( %x , %s , %d )\n", $base, $pfx, $id);
...
	$list_fmt = array(
		44 => ? , 
		0x49 => 'im_bc4',
		0x4d => 'im_bc7',
	);
	if ( ! isset($list_fmt[$fmt]) )
		return php_error('UNKNOWN im fmt  %x', $fmt);
	printf("DETECT  fmt %s , %x x %x \n", $list_fmt[$fmt], $w, $h);
...
}
```
![Snipaste_2024-06-05_14-23-53](https://github.com/rufaswan/Web2D_Games/assets/55184223/9087eaff-5183-4452-9641-80d81aa8c27a)

[SecretFile.zip](https://github.com/user-attachments/files/15574154/SecretFile.zip)

**Comment by ZzzzzzzSkyward** [comment]
Hello, I want to seek further help regarding 13 sentinels. Actually I am able to extract the animation, despite a bit bug, but the problem is that in the activation animation, there are images elsewhere, which I don't know where to get it. Is it possible to figure out what is missing?
![Snipaste_2024-06-06_19-47-32](https://github.com/rufaswan/Web2D_Games/assets/55184223/fe7916ee-fa8b-4966-8cc4-161793cbd34e)
[Shinonome.zip](https://github.com/user-attachments/files/15614650/Shinonome.zip)
While it is interesting that Fuyusaka does have some "START" sign stored in her own sprites.
![fuyusaka](https://github.com/rufaswan/Web2D_Games/assets/55184223/52ae120f-6548-4a18-b15a-d57060db94e4)

**Comment by rufaswan** [comment]
Interesting. I must have missed checking those FTX files. 0x44 is BC3 or DXT5 encoding, and the script is updated to support those files. Thanks!

**Comment by rufaswan** [comment]
You mean connecting different QUAD files, like Momohime here?

#18 

That whole thing is currently under research.

**Comment by ZzzzzzzSkyward** [comment]
Yes, the first task is to find out where the missing images are stored, and next join two files. It is common for 2D animations to split sprites into multiple files. However, I'm not familiar with such format and cannot find what I want, that is **the name of the layer/image**. So I come to ask.
By the way, the animation exported now looks broken. It is not as smooth as I can tell from the game, maybe there is a need for interpolation.

**Comment by rufaswan** [comment]
Should be something like this : https://github.com/rufaswan/Web2D_Games/issues/12#issuecomment-2061404320

The animation data is debug using PS2 Odin Sphere, and since PS3/PS4/Vita Odin Sphere remake, Vanillaware have upgraded the MBS file with a bunch of new stuff I yet known or support. I am not surprise the animation is broken since then.
